spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.69.59:3306/dm?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Admin@123
  redis:
    host: 47.104.69.59
    port: 63790
    database: 0
    password: Admin@123
    jpa:
        show-sql: true

mybatis:
  mapper-locations: classpath:mapping/*.xml


